version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb2
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test_db
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: